#!/bin/env php 
<?php
/**
 * 
 * @fileName baike.php
 * @category PHP
 * @package void
 * @author Kee Guo <chinboy2012@gmail.com> 2017年05月15日 星期一 22时46分55秒
 * @since 15/05/2017
 * @version baike.php 2017.05.15
 * */
$args = $argv;
array_shift($args);
if (!isset($args[0])) exit("没有要查询的关键字\r\n");
$key = $args[0];
$url = 'http://baike.baidu.com/item/' . $key;

$body = file_get_contents($url);

preg_match_all('/\<div class="para" label-module="para">(.*)\<\/div>/Uis', $body, $match);

if (!isset($match[1])) exit("词条还未被创建\r\n");

echo "$key\r\n";
echo "词条释义: \r\n";
foreach ($match[1] as $para) {
  $para = strip_tags($para);
  echo $para . "\r\n";
}
