#!/usr/bin/env php
<?php
/**
 * 
 * @fileName bin.php
 * @category PHP
 * @package void
 * @author Kee Guo <chinboy2012@gmail.com> 2016年10月25日 星期二 00时14分48秒
 * @since 25/10/2016
 * @version bin.php 2016.10.25
 * */
$md = @$argv[1];
if (!$md) exit("Not input file \r\n");
//if (!file_exists($md)) exit("is not file \r\n");
$name = basename($md);
$md = file_get_contents($md);
$cc = file_get_contents(__DIR__ . '/template.html');
$cc = str_replace('#markdown-text', $md, $cc);
$cc = str_replace('#title', $name, $cc);
$cc = str_replace("\r", "", $cc);
file_put_contents(__DIR__ . '/preview.html', $cc);
shell_exec('google-chrome --start-maximized --app="file://'.__DIR__.'/preview.html" > /dev/null &');
